pr: none
trigger: 
- main

parameters:
  - name: location
    type: string
    default: 'westeurope'

variables:
  - name: subscription_name
    value: AzureRM SvcConnection JMB-DPL-SDLZ-TST

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    
    - task: ps-rule-assert@2
      displayName: Run PSRule analysis
      continueOnError: true    
      inputs:
        inputType: repository
        modules: 'PSRule.Rules.Azure'
        outputFormat: NUnit3
        outputPath: reports/ps-rule-results.xml  

    - task: PublishTestResults@2
      displayName: "Publish PSRule results"
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: 'reports/ps-rule-results.xml'
        failTaskOnFailedTests: false
        testRunTitle: 'PSRule-File'
    
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(subscription_name) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file infra/main.bicep'

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/infra/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/infra/main.params.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 

- stage: CD
  variables:
  - group: "Terraform Vars TST"
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(subscription_name) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                 az --version
                 az login --service-principal -u '$(contributor-app-registration-id)' -p '$(contributor-service-principal-secret)' --tenant $(tenant-id)
                 az deployment sub create --location ${{ parameters.location }} `
                 --template-file $(Build.SourcesDirectory)/infra/main.bicep `
                 --parameters $(Build.SourcesDirectory)/infra/main.params.json