trigger:
- none

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: DEV
  variables:
  - group: Custom Terraform Vars DEV
  - name: environment
    value: DEV
  steps:
  - script: echo "ssql is $(sdlz-metadata-d-sqldb-001-admin-password) in enviroment $(environment)"