trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: "Custom Terraform Vars DEV"

stages:
  - stage: test
    jobs:
    - job:
      displayName: Retrieve variables
      steps:
        - task: Powershell@2
          displayName: Variable retrieval
          inputs:
            targetType: inline
            script: |
              $SqlAdminVarName = '$(metadataSqlServerName)' + "-admin-username"
              Write-Host "Direct access: $(SqlAdminVarName)"