trigger:
- none

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: DEV
  variables:
  - group: Custom Terraform Vars DEV
  - name: environment
    value: DEV
  - name: SqlDbName
    value: 'sdlz-metadata-d-sqldb-001'
  - name: PostFix
    value: '-admin-password'
  - name: SqlPasswordName
    value: $(SqlDbName)$(PostFix)
  steps:
  - script: echo "ssql is $(SqlPasswordName) in enviroment $(environment)"