trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: Custom Terraform Vars DEV
#- name: my-passed-variable
#  value: $[variables.format('$(metadataSqlServerName)' + "-admin-username") ] # uses runtime expression

steps:  
- script: echo $(sdlz-metadata-p-sqldb-001-admin-username) # uses macro syntax
- script: echo $(my-passed-variable) 


