trigger:
- none

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: DEV
  variables:
  - group: Custom Terraform Vars DEV
  - name: environment
    value: DEV
  - name: SqlDbName
    value: 'sdlz-metadata-d-sqldb-001'
  - name: PostFix
    value: '-admin-password'
  - name: SqlPasswordName
    value: $(SqlDbName)$(PostFix)
  steps:
    - task: AzureKeyVault@2
      inputs:
          azureSubscription: 'sandbox-data-management-landing-zone-dev-to-JMB-JDC-DMZL-DEV'
          KeyVaultName: 'dmlz-shir-dev-kv'
          SecretsFilter: '*'